theme: jekyll-theme-minimal
title: OR3on的博客
logo: https://cdn.jsdelivr.net/gh/Austyncleo/Img_picgo@main/notes/course/avatar.jpg
lang: zh-CN
author: or3on
description: OR3on's Home Page
timezone: Asia/Shanghai
excerpt_separator: <!--more-->
paginate: 7
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
feed:
  path: atom.xml
webmaster_verifications:
  google:  
  yandex:  
  bing:  
social:
  name: OR3on
  links:
    - https://github.com/s1xnEvo
google_analytics: UA-137710294-1
